### ISSUE TITLE
Tarea: Listar los usuarios conectados

### ISSUE THREAD

**Issue by ofidord** [Dibad/Proyecto-FIS#10]
## Información:

__Tarea a realizar:__ Ver que usuarios están conectados al servidor.

__Medios:__  Cada cliente le envía un mensaje al servidor y el servidor le reenvía los usuarios que tiene, el servidor deberá tener una lista de las ips conectadas y el usuario está asociado a cada ip.

__Funcionamiento esperado:__  Cuando el cliente envíe el comando "?:lista" el servidor deberá enviarle la ip y el usuario de los usuarios conectados.

## Incluido en:
Esta Tarea de Programación pertenece a las siguentes Historias de Usuario:
* [Característica: Ver que usuarios están conectados](https://github.com/Dibad/Proyecto-FIS/issues/9)

**Comment by Dibad** [comment]
Completado en https://github.com/Dibad/Proyecto-FIS/commit/2bbb8b6b2e094e565629478e441186c54b132037
