### ISSUE TITLE
Tarea: Incluir nombre de usuario junto al mensaje

### ISSUE THREAD

**Issue by ofidord** [Dibad/Proyecto-FIS#8]
## Información:

__Tarea a realizar:__ Permitir que cada usuario tengo un nombre con el que registrarse.

__Medios:__ Cuando se envíe un mensaje se incluirá el nombre del usuario. 

__Funcionamiento esperado:__ Al conectarse un cliente se le pedirá el nombre de usuario correspondiente y al mandar un mensaje aparecerá junto al mismo.
Estructura: "[usuario] dijo: [mensaje]"

## Incluido en:
Esta Tarea de Programación pertenece a las siguentes Historias de Usuario:
* [Característica: Nombre de usuario](https://github.com/Dibad/Proyecto-FIS/issues/7)
* [Característica: Ver que usuarios están conectados](https://github.com/Dibad/Proyecto-FIS/issues/9)

**Comment by Dibad** [comment]
Completado en https://github.com/Dibad/Proyecto-FIS/commit/bc7e0e93a5250b607ba0f9d467631593c4e36fe2
